<?php
use Rocco\ArangoORM\DB\DB;
use Rocco\ArangoORM\Models\Core\EdgeModel;

/**
 *  Corresponding Class to test YourClass class
 *
 *  For each class in your library, there should be a corresponding Unit-Test for it
 *  Unit-Tests should be as much as possible independent from other test going on.
 *
 * @author yourname
 */
class BaseTest extends PHPUnit_Framework_TestCase
{

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $connection_settings = require __DIR__ . '/data/database_settings.php';
        DB::connect($connection_settings);
    }

    public function testConnection()
    {
        $connection_settings = require __DIR__ . '/data/database_settings.php';
        DB::connect($connection_settings);

        $ch = DB::getCollectionHandler();
        if (!$ch->has("users")) $ch->create("users");

        $cursor = DB::getAll("users");
        self::assertNotEquals(null, $cursor);
        $ch->drop("users");
    }

}