<?php
use vector\ArangoORM\DB\DB;


class BaseTest extends PHPUnit_Framework_TestCase
{

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $connection_settings = require __DIR__ . '/data/database_settings.php';
        DB::connect($connection_settings);
    }

    public function testConnection()
    {
        $connection_settings = require __DIR__ . '/data/database_settings.php';
        DB::connect($connection_settings);

        $ch = DB::getCollectionHandler();
        DB::createCollectionIfNotExsists( "users" );

        $cursor = DB::getAll("users");
        self::assertNotEquals(null, $cursor);
        $ch->drop("users");
    }

}