<?php
use rocco\ArangoORM\DB\DB;

/**
*  Corresponding Class to test YourClass class
*
*  For each class in your library, there should be a corresponding Unit-Test for it
*  Unit-Tests should be as much as possible independent from other test going on.
*
*  @author yourname
*/
class ModelsTest extends BaseTest {

    static $test_vertex = "im_a_vertex_collection";
    static $test_edge = "im_an_edge_collection";


    function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $ch = DB::getCollectionHandler();
        $ch->create( self::$test_vertex );
    }

    function tearDown()
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
        $ch = DB::getCollectionHandler();
        $ch->drop( self::$test_vertex );
    }

    function testConstruct(){

        $vertexOne = TestVertexModel::create( [
            "name"  =>  "Vertex One"
        ] );
        $vertexTwo = TestVertexModel::create( [
            "name"  =>  "Vertex Two"
        ] );
        $edge = TestEdgeModel::create(
            $vertexOne, $vertexTwo,
            [
                "name"  =>  "optional"
            ]
        );

        $cursor = DB::getAll( TestVertexModel::$collection );
        self::assertTrue( $cursor->getCount() > 0 );
        self::assertInstanceOf( TestEdgeModel::class, $edge );
    }

}

class TestVertexModel extends \rocco\ArangoORM\Models\Core\VertexModel {
    static $collection = "im_a_vertex_collection";
}
class TestEdgeModel extends \rocco\ArangoORM\Models\Core\EdgeModel {
    static $collection = "im_an_edge_collection";
}